theme = "gruvbox_transparent"

[editor]
line-number = "relative"
bufferline = "multiple"
completion-timeout = 5

[editor.lsp]
auto-signature-help = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
C-g = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output lazygit',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
tab = "goto_next_buffer"
S-tab = "goto_previous_buffer"
space.x = ":buffer-close"

